services:
    ChatSample.cqrs:
        image: ${DOCKER_REGISTRY-}chatsamplecqrs
        build:
          context: ../ChatSampleCQRS
          dockerfile: ./ChatSample.CQRS/Dockerfile
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=https://+:443;http://+:80;http://+:8080;https://+:8081
          - ASPNETCORE_Kestrel__Certificates__Default__Password=thisIsAPass
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
          - RUNNING_ON_DOCKER=true
          - SEED=true 
        volumes:
          - ~/.aspnet/https:/https:ro
        depends_on:
          - cqrsdata
    cqrsdata:
      image: mcr.microsoft.com/mssql/server:2019-latest
      environment:
        - SA_PASSWORD=Pass@word
        - ACCEPT_EULA=Y
      ports:
        - "5434:1433"
      volumes:
        - cqrs:/home/cqrs/db  
    rabbitmq:
        image: rabbitmq:3-management
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
volumes:
  cqrs: